name: Action2

on:
  workflow_run:
    workflows: ["Action1"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: "Display Github Event"
        run: |
          echo "Event: ${{ github.event_name }}"
        shell: bash

      - name: "Checkout workflow_dispatch GitHub Action"
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Checkout workflow_run GitHub Action"
        if: github.event_name == 'workflow_run'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0

      - name: "Display workflow_run head_branch"
        if: github.event_name == 'workflow_run'
        run: |
          echo "Json: ${{ github.event.workflow_run }}"
        shell: bash

      - name: "Display Branch"
        run: |
          git branch
        shell: bash

      - name: "Display Version"
        run: |
          cat ver.txt
        shell: bash
